"""created a timezone mixin for users table

Revision ID: 0461352d3f4d
Revises: f1990d4e3440
Create Date: 2025-06-03 17:25:04.481574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0461352d3f4d'
down_revision = 'f1990d4e3440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modifeid', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_date_created'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_date_created'), ['date_created'], unique=False)
        batch_op.drop_column('date_modifeid')

    # ### end Alembic commands ###
