"""Adjust user table

Revision ID: 99822440adb6
Revises: bf5fef2d33ba
Create Date: 2025-06-02 20:13:39.493989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99822440adb6'
down_revision = 'bf5fef2d33ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
